apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
  labels:
    app: ${APPLICATION}
spec:
  ports:
    - port: ${DB_PORT}
  selector:
    app: ${APPLICATION}
    tier: ${DATABASE}
  clusterIP: None
