apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${DB_CLAIM_NAME}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${DB_STORAGE}
