apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${DB_CLAIM_NAME}
  labels:
    app: ${APPLICATION}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
