apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${DB_CLAIM_NAME}
  labels:
    app: ${APPLICATION}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${DB_STORAGE}
parameters:
- description: Volume space available for data, e.g. 512Mi, 2Gi
  displayName: Volume Capacity
  name: DB_STORAGE
  value: 20Gi
- description: Application-name
  displayName: label-Application-name
  name: APPLICATION
  value: wordpress
- description: Application name
  displayName: Claim-DB- Name
  name: DB_CLAIM_NAME
  value: mysql-pv-claim
