apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP_CLAIM_NAME}
  labels:
    app: ${APPLICATION}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${APP_STORAGE}
